const Map<String, String> ar = {
  'cat': 'قط',
  'dog': 'كلب',
  'bird': 'طير',
  'cats': 'قطط',
  'dogs': 'كلاب',
  'birds': 'طيور',
  'enterYourQuestion': 'ادخل سؤالك',
  'types': 'انواع',
  'foods': 'طعام',
  'addImg': 'أضف صورة',
  'equipments': 'معدات',
  'addConsult': 'أضف استشارة',
  'photo_from': 'إختر الصورة من',
  'consulting': 'استشارة',
  'addConsulting': 'إضافة استشارة',
   'username':'اسم المستخدم',
   'pass':'كلمة المرور',
   'confirm':'تأكيد كلمة المرور',
   'login':'تسجيل الدخول',
   'register':'التسجيل',
   'email':'البريد الاكتروني',
   'notMatch':'كلمتي المرور غير متطابقتين',
  'invalidEmail':'البريد الاكتروني غير صالح',
  'passShort':'كلمة المرور قصيرة جدا',
};
