const Map<String, String> en = {
  'cat':'Cat',
  'dog':'Dog',
  'bird':'Bird',
  'cats':'Cats',
  'dogs':'Dogs',
  'birds':'Birds',
  'types': 'Types',
  'foods': 'Foods',
  'enterYourQuestion': 'Enter Your Question',
  'addImg': 'add an Image',
  'equipments': 'Equipments',
  'consulting': 'Consulting',
  'addConsulting': 'Add Consulting',
  'addConsult': 'Add Consult',
  'photo_from': 'Choose photo from',
  'username':'Username',
  'pass':'Password',
  'confirm':'Confirm Password',
  'login':'Login',
  'register':'Register',
  'email':'Email',
  'invalidEmail':'Invalid Email',
  'passShort':'Password is too short!',
  'notMatch':'Not Match!',
};